TrajectoryPlannerROS:
  max_vel_x: 0.2
  min_vel_x: 0

  max_vel_theta: 3.0
  min_vel_theta: -3.0
  min_in_place_vel_theta: 1.0

  xy_goal_tolerance: 0.30
  yaw_goal_tolerance: 0.5

  acc_lim_theta: 0.6
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  holonomic_robot: false

