obstacle_range: 0.75
raytrace_range: 0.75  #made mistake here. should be smaller than width in local costmap params 
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.17
transform_tolerance: 0.5
inflation_radius: 0.12

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan,
                topic: scan, marking: true, clearing: true}

